export interface Service {
  slug: string
  slugEs: string
  name: string
  nameEs: string
  shortDesc: string
  shortDescEs: string
  description: string
  descriptionEs: string
  icon: string
  image: string
}

export const services: Service[] = [
  {
    slug: 'car-lockout',
    slugEs: 'apertura-de-auto',
    name: 'Car Lockout',
    nameEs: 'Apertura de Auto',
    shortDesc: 'Locked your keys in the car? We\'ll get you back on the road quickly and safely.',
    shortDescEs: '¿Dejó las llaves en el auto? Le ayudamos a regresar al camino rápido y sin daños.',
    description: 'Getting locked out of your car is stressful, but Aledo Locksmith makes it easy. Our trained technicians use professional, non-damaging tools to unlock your vehicle quickly — no scratches, no broken windows. We handle all car makes and models and are available 24/7 for emergencies in Aledo, TX and the surrounding 10-mile area. Call or text us and we\'ll be there fast.',
    descriptionEs: 'Quedarse encerrado fuera de su auto es estresante, pero Aledo Locksmith lo hace fácil. Nuestros técnicos capacitados usan herramientas profesionales que no dañan su vehículo para abrirlo rápidamente. Manejamos todas las marcas y modelos y estamos disponibles 24/7 para emergencias en Aledo, TX y el área de 10 millas.',
    icon: 'Car',
    image: '/images/car-lockout-service-aledo-tx.png',
  },
  {
    slug: 'car-key-replacement',
    slugEs: 'reemplazo-de-llave-de-auto',
    name: 'Car Key Replacement',
    nameEs: 'Reemplazo de Llave de Auto',
    shortDesc: 'Lost or broken car key? We cut and program new keys for all makes and models.',
    shortDescEs: '¿Perdió o se le rompió la llave del auto? Cortamos y programamos llaves nuevas para todas las marcas.',
    description: 'Whether you\'ve lost your only car key, broken it, or need a spare, our car key replacement service has you covered. We cut and program standard, transponder, and high-security car keys on-site for all major makes and models. Fast mobile service in Aledo, TX and within a 10-mile radius — we come to you so you don\'t need a tow.',
    descriptionEs: 'Ya sea que perdió su única llave del auto, se le rompió, o necesita una copia, nuestro servicio de reemplazo de llave de auto le tiene cubierto. Cortamos y programamos llaves estándar, de transponder y de alta seguridad en el lugar para todas las marcas principales. Servicio móvil rápido en Aledo, TX y dentro de un radio de 10 millas.',
    icon: 'KeyRound',
    image: '/images/new-car-keys-replacement-aledo-tx.png',
  },
  {
    slug: 'key-fob-programming',
    slugEs: 'programacion-de-control-remoto',
    name: 'Key Fob Programming',
    nameEs: 'Programación de Control Remoto',
    shortDesc: 'Need a new key fob or remote? We program fobs for most vehicle brands.',
    shortDescEs: '¿Necesita un control remoto nuevo? Programamos controles para la mayoría de marcas.',
    description: 'Modern vehicles rely on key fobs and smart remotes for keyless entry and push-button start. If your fob is lost, damaged, or stops working, we can program a new one on the spot. Our technicians carry the latest equipment to program key fobs for most vehicle brands including Ford, Chevy, Toyota, Honda, Nissan, and more. Serving Aledo, TX and nearby areas.',
    descriptionEs: 'Los vehículos modernos dependen de controles remotos y llaves inteligentes para entrada sin llave y encendido por botón. Si su control se perdió, se dañó o dejó de funcionar, podemos programar uno nuevo en el lugar. Nuestros técnicos llevan el equipo más reciente para programar controles remotos de la mayoría de marcas incluyendo Ford, Chevy, Toyota, Honda, Nissan y más. Servicio en Aledo, TX y áreas cercanas.',
    icon: 'Lock',
    image: '/images/key-fob-programming-service-aledo-tx.png',
  },
  {
    slug: 'transponder-key-programming',
    slugEs: 'programacion-de-llave-transponder',
    name: 'Transponder Key Programming',
    nameEs: 'Programación de Llave Transponder',
    shortDesc: 'We program transponder chip keys so your car recognizes and starts with the new key.',
    shortDescEs: 'Programamos llaves con chip transponder para que su auto reconozca e inicie con la nueva llave.',
    description: 'Most cars built after 1995 use transponder chip keys as an anti-theft measure. If the chip isn\'t programmed correctly, the car won\'t start. Our automotive locksmith team programs transponder keys on-site using professional-grade equipment. We work with all major vehicle brands and can have your new key working in minutes. Available in Aledo, TX and within 10 miles.',
    descriptionEs: 'La mayoría de autos fabricados después de 1995 usan llaves con chip transponder como medida antirrobo. Si el chip no está programado correctamente, el auto no enciende. Nuestro equipo de cerrajería automotriz programa llaves transponder en el lugar usando equipo profesional. Trabajamos con todas las marcas principales y podemos tener su nueva llave funcionando en minutos. Disponible en Aledo, TX y dentro de 10 millas.',
    icon: 'Siren',
    image: '/images/transponder-key-cutting-aledo-tx.png',
  },
  {
    slug: 'ignition-repair',
    slugEs: 'reparacion-de-ignicion',
    name: 'Ignition Repair & Replacement',
    nameEs: 'Reparación y Reemplazo de Ignición',
    shortDesc: 'Key won\'t turn in the ignition? We repair and replace ignition cylinders on-site.',
    shortDescEs: '¿La llave no gira en la ignición? Reparamos y reemplazamos cilindros de ignición en el lugar.',
    description: 'A faulty ignition cylinder can leave you stranded. Whether your key is stuck, the ignition won\'t turn, or the cylinder is worn out, our mobile locksmith team can diagnose and repair or replace your ignition on-site. We carry parts for most popular vehicle brands and get you back on the road fast. Serving Aledo, TX and the surrounding area.',
    descriptionEs: 'Un cilindro de ignición defectuoso puede dejarlo varado. Ya sea que su llave esté atorada, la ignición no gire, o el cilindro esté desgastado, nuestro equipo móvil de cerrajería puede diagnosticar y reparar o reemplazar su ignición en el lugar. Llevamos partes para las marcas de vehículos más populares y lo ponemos en el camino rápidamente. Servicio en Aledo, TX y el área circundante.',
    icon: 'Wrench',
    image: '/images/ignition-repair-replacement-aledo-tx.png',
  },
  {
    slug: 'emergency-car-locksmith',
    slugEs: 'cerrajero-automotriz-de-emergencia',
    name: 'Emergency Car Locksmith (24/7)',
    nameEs: 'Cerrajero Automotriz de Emergencia (24/7)',
    shortDesc: 'Stranded with a car key emergency? We respond 24/7, day or night.',
    shortDescEs: '¿Varado con una emergencia de llave de auto? Respondemos 24/7, de día o de noche.',
    description: 'Car key emergencies don\'t wait for business hours. Whether you\'re locked out at midnight, broke your key in the ignition, or lost your only key at a parking lot, our 24/7 emergency automotive locksmith service is here for you. We arrive fast — typically within 20-30 minutes in the Aledo area — with all the tools needed to solve your problem on the spot.',
    descriptionEs: 'Las emergencias de llaves de auto no esperan al horario de oficina. Ya sea que esté encerrado a medianoche, se le rompió la llave en la ignición, o perdió su única llave en un estacionamiento, nuestro servicio de cerrajería automotriz de emergencia 24/7 está aquí para usted. Llegamos rápido — generalmente en 20-30 minutos en el área de Aledo — con todas las herramientas necesarias para resolver su problema en el lugar.',
    icon: 'Siren',
    image: '/images/emergency-locksmith-technician-night-aledo-tx.png',
  },
  {
    slug: 'trunk-lockout',
    slugEs: 'apertura-de-cajuela',
    name: 'Trunk Lockout',
    nameEs: 'Apertura de Cajuela',
    shortDesc: 'Keys locked in the trunk? We open it without damage to your vehicle.',
    shortDescEs: '¿Llaves encerradas en la cajuela? La abrimos sin dañar su vehículo.',
    description: 'Accidentally locking your keys in the trunk is frustrating, especially when you\'re in a rush. Our technicians specialize in trunk lockout service and use non-destructive methods to access your trunk safely. We work with all vehicle types — sedans, SUVs, trucks — and arrive quickly in the Aledo, TX area. No damage, no hassle.',
    descriptionEs: 'Encerrar accidentalmente las llaves en la cajuela es frustrante, especialmente cuando tiene prisa. Nuestros técnicos se especializan en apertura de cajuela y usan métodos no destructivos para acceder a su cajuela de forma segura. Trabajamos con todo tipo de vehículos — sedanes, SUVs, camionetas — y llegamos rápido en el área de Aledo, TX. Sin daños, sin complicaciones.',
    icon: 'Car',
    image: '/images/emergency-car-lockout-night-aledo-tx.png',
  },
  {
    slug: 'broken-car-key-extraction',
    slugEs: 'extraccion-de-llave-de-auto-rota',
    name: 'Broken Car Key Extraction',
    nameEs: 'Extracción de Llave de Auto Rota',
    shortDesc: 'Key snapped in the door or ignition? We extract it safely and cut a new one.',
    shortDescEs: '¿Se le rompió la llave en la puerta o ignición? La extraemos y cortamos una nueva.',
    description: 'A car key breaking in the door lock or ignition cylinder is more common than you think. Trying to remove it yourself can push the broken piece further in and cause expensive damage. Our automotive locksmith team uses specialized extraction tools to safely remove the broken key fragment and can cut you a brand new key on the spot. Serving Aledo, TX and nearby areas.',
    descriptionEs: 'Una llave de auto que se rompe en la cerradura de la puerta o el cilindro de ignición es más común de lo que piensa. Intentar sacarla usted mismo puede empujar la pieza rota más adentro y causar daños costosos. Nuestro equipo de cerrajería automotriz usa herramientas de extracción especializadas para remover el fragmento de forma segura y puede cortarle una llave nueva en el lugar. Servicio en Aledo, TX y áreas cercanas.',
    icon: 'Wrench',
    image: '/images/car-key-cutting-machine-aledo-tx.png',
  },
  {
    slug: 'duplicate-car-keys',
    slugEs: 'duplicado-de-llaves-de-auto',
    name: 'Duplicate Car Keys',
    nameEs: 'Duplicado de Llaves de Auto',
    shortDesc: 'Need a spare car key? We make duplicates on-site for all vehicle types.',
    shortDescEs: '¿Necesita una copia de llave de auto? Hacemos duplicados en el lugar para todo tipo de vehículo.',
    description: 'Having a spare car key can save you from an expensive emergency lockout later. We provide on-site car key duplication for standard metal keys, transponder chip keys, and high-security keys. Our mobile unit comes to your location in Aledo, TX and nearby areas, equipped with professional key cutting and programming machines. Fast, affordable, and convenient.',
    descriptionEs: 'Tener una copia de llave de auto puede ahorrarle una apertura de emergencia costosa en el futuro. Proporcionamos duplicado de llaves de auto en el lugar para llaves metálicas estándar, llaves con chip transponder y llaves de alta seguridad. Nuestra unidad móvil va a su ubicación en Aledo, TX y áreas cercanas, equipada con máquinas profesionales de corte y programación. Rápido, accesible y conveniente.',
    icon: 'KeyRound',
    image: '/images/locksmith-delivering-car-keys-customer-aledo-tx.png',
  },
  {
    slug: 'ecu-programming',
    slugEs: 'programacion-de-ecu',
    name: 'ECU & Computer Programming',
    nameEs: 'Programación de ECU y Computadora',
    shortDesc: 'Advanced ECU programming and automotive computer services for all vehicles.',
    shortDescEs: 'Programación avanzada de ECU y servicios de computadora automotriz para todos los vehículos.',
    description: 'Our ECU (Engine Control Unit) programming service covers everything from reflashing factory software to programming replacement modules. Whether you need a new ECU synced to your vehicle\'s immobilizer, a used ECU coded to your VIN, or diagnostic fault clearing, our technicians have dealer-level tools and expertise. We handle all makes and models on-site in Aledo, TX and within a 10-mile radius — no tow to the dealer needed.',
    descriptionEs: 'Nuestro servicio de programación de ECU (Unidad de Control del Motor) cubre todo, desde reprogramar software de fábrica hasta programar módulos de reemplazo. Ya sea que necesite una nueva ECU sincronizada con el inmovilizador de su vehículo, una ECU usada codificada a su VIN, o limpieza de fallas diagnósticas, nuestros técnicos tienen herramientas y experiencia de nivel concesionario. Manejamos todas las marcas y modelos en el lugar en Aledo, TX y dentro de un radio de 10 millas.',
    icon: 'Cpu',
    image: '/images/smart-key-diagnostic-tablet-aledo-tx.png',
  },
  {
    slug: 'smart-key-programming',
    slugEs: 'programacion-de-llave-inteligente',
    name: 'Smart Key & Keyless Entry',
    nameEs: 'Llave Inteligente y Entrada Sin Llave',
    shortDesc: 'Smart key programming, keyless entry, and push-to-start system services.',
    shortDescEs: 'Programación de llave inteligente, entrada sin llave y servicios de encendido por botón.',
    description: 'Modern vehicles use smart keys and proximity fobs for keyless entry and push-button start. If your smart key is lost, damaged, or needs replacement, we program new ones on-site using the latest equipment. We support all major brands including Toyota, Honda, Nissan, Hyundai, Kia, Ford, and luxury marques. Mobile service available in Aledo, TX and nearby areas — fast, convenient, and significantly cheaper than the dealership.',
    descriptionEs: 'Los vehículos modernos usan llaves inteligentes y controles de proximidad para entrada sin llave y encendido por botón. Si su llave inteligente se perdió, se dañó o necesita reemplazo, programamos nuevas en el lugar usando el equipo más reciente. Soportamos todas las marcas principales incluyendo Toyota, Honda, Nissan, Hyundai, Kia, Ford y marcas de lujo. Servicio móvil disponible en Aledo, TX y áreas cercanas — rápido, conveniente y significativamente más económico que el concesionario.',
    icon: 'Smartphone',
    image: '/images/car-smart-key-system-aledo-tx.png',
  },
  {
    slug: 'module-programming',
    slugEs: 'programacion-de-modulos',
    name: 'ECM/TCM/BCM/ABS Module Programming',
    nameEs: 'Programación de Módulos ECM/TCM/BCM/ABS',
    shortDesc: 'Advanced control module programming for ECM, TCM, BCM, and ABS systems — all makes and models.',
    shortDescEs: 'Programación avanzada de módulos de control ECM, TCM, BCM y ABS — todas las marcas y modelos.',
    description: 'When a vehicle\'s control module fails or needs replacement, it must be programmed to communicate with the rest of the car\'s systems. We program Engine Control Modules (ECM), Transmission Control Modules (TCM), Body Control Modules (BCM), and ABS modules for all years, makes, and models. Our dealer-level equipment handles VIN writing, parameter configuration, and module initialization. Serving Aledo, TX and the surrounding area.',
    descriptionEs: 'Cuando un módulo de control de un vehículo falla o necesita reemplazo, debe ser programado para comunicarse con el resto de los sistemas del auto. Programamos Módulos de Control del Motor (ECM), Módulos de Control de Transmisión (TCM), Módulos de Control de Carrocería (BCM), y módulos ABS para todos los años, marcas y modelos. Nuestro equipo de nivel concesionario maneja escritura de VIN, configuración de parámetros e inicialización de módulos. Servicio en Aledo, TX y el área circundante.',
    icon: 'Cpu',
    image: '/images/mobile-key-programming-workstation-aledo-tx.png',
  },
  {
    slug: 'airbag-reset-crash-module',
    slugEs: 'reseteo-de-airbag-y-modulo-de-choque',
    name: 'Airbag Reset & Crash Module Repair',
    nameEs: 'Reseteo de Airbag y Reparación de Módulo de Choque',
    shortDesc: 'Professional airbag module reset and crash data clearing after accidents.',
    shortDescEs: 'Reseteo profesional de módulo de airbag y limpieza de datos de choque después de accidentes.',
    description: 'After a collision, your vehicle\'s airbag control module stores crash data and fault codes that keep the SRS warning light on. Rather than buying an expensive new module from the dealer, we can reset your existing module by clearing the crash data and restoring it to factory condition. This service works on virtually all vehicle makes and models. Fast turnaround, mobile service in Aledo, TX and nearby areas.',
    descriptionEs: 'Después de una colisión, el módulo de control de airbag de su vehículo almacena datos de choque y códigos de falla que mantienen la luz de advertencia SRS encendida. En lugar de comprar un módulo nuevo costoso del concesionario, podemos resetear su módulo existente limpiando los datos de choque y restaurándolo a condición de fábrica. Este servicio funciona en prácticamente todas las marcas y modelos. Servicio rápido y móvil en Aledo, TX y áreas cercanas.',
    icon: 'Shield',
    image: '/images/automotive-locksmith-mobile-workshop-aledo-tx.png',
  },
  {
    slug: 'mercedes-elv-steering-lock-repair',
    slugEs: 'reparacion-de-cerradura-de-direccion-mercedes-elv',
    name: 'Mercedes ELV Steering Lock Repair',
    nameEs: 'Reparación de Cerradura de Dirección Mercedes ELV',
    shortDesc: 'Expert Electronic Steering Lock (ELV) repair and replacement for Mercedes-Benz.',
    shortDescEs: 'Reparación y reemplazo experto de Cerradura Electrónica de Dirección (ELV) para Mercedes-Benz.',
    description: 'The Electronic Steering Lock (ELV) is a known failure point on Mercedes-Benz W204 C-Class, W207 E-Class Coupe, and W212 E-Class models. When it fails, the steering wheel locks and the car won\'t start. We repair and replace ELV modules on-site, program them to your vehicle, and restore full functionality — no flatbed to the dealer required. Serving Aledo, TX and nearby areas.',
    descriptionEs: 'La Cerradura Electrónica de Dirección (ELV) es un punto de falla conocido en los modelos Mercedes-Benz W204 Clase C, W207 Clase E Coupé y W212 Clase E. Cuando falla, el volante se bloquea y el auto no enciende. Reparamos y reemplazamos módulos ELV en el lugar, los programamos a su vehículo y restauramos la funcionalidad completa — sin necesidad de grúa al concesionario. Servicio en Aledo, TX y áreas cercanas.',
    icon: 'Car',
    image: '/images/smart-key-programming-luxury-car-aledo-tx.png',
  },
  {
    slug: 'bmw-frm-repair',
    slugEs: 'reparacion-de-modulo-frm-bmw',
    name: 'BMW FRM Footwell Module Repair',
    nameEs: 'Reparación de Módulo FRM BMW',
    shortDesc: 'Professional BMW FRM (Footwell Module) repair and programming services.',
    shortDescEs: 'Servicios profesionales de reparación y programación de módulo FRM (Módulo de Piso) BMW.',
    description: 'The BMW FRM (Footwell Module) controls headlights, tail lights, turn signals, power windows, and other electrical functions. Water damage, electrical surges, or age can cause FRM failure — leading to lighting malfunctions and warning lights. We repair FRM circuit boards, replace faulty components, and reprogram the module to your vehicle. On-site service in Aledo, TX and within 10 miles.',
    descriptionEs: 'El FRM (Módulo de Piso) de BMW controla faros, luces traseras, direccionales, ventanas eléctricas y otras funciones eléctricas. Daño por agua, sobrecarga eléctrica o antigüedad pueden causar falla del FRM — provocando mal funcionamiento de luces y advertencias. Reparamos circuitos del FRM, reemplazamos componentes defectuosos y reprogramamos el módulo a su vehículo. Servicio en el lugar en Aledo, TX y dentro de 10 millas.',
    icon: 'Wrench',
    image: '/images/smart-key-programming-luxury-car-aledo-tx.png',
  },
  {
    slug: 'saab-steering-lock-bypass',
    slugEs: 'bypass-de-cerradura-de-direccion-saab',
    name: 'Saab Steering Lock Bypass',
    nameEs: 'Bypass de Cerradura de Dirección Saab',
    shortDesc: 'Expert Saab steering column lock bypass and repair — permanent solution.',
    shortDescEs: 'Bypass y reparación experta de cerradura de columna de dirección Saab — solución permanente.',
    description: 'Saab vehicles are prone to steering column lock failures that prevent the car from starting. Rather than expensive dealer replacements, we offer a professional permanent bypass solution that eliminates the problem for good. Our technicians handle all Saab models and complete the repair on-site. Serving Aledo, TX and the surrounding area.',
    descriptionEs: 'Los vehículos Saab son propensos a fallas en la cerradura de la columna de dirección que impiden que el auto encienda. En lugar de reemplazos costosos del concesionario, ofrecemos una solución profesional de bypass permanente que elimina el problema definitivamente. Nuestros técnicos manejan todos los modelos Saab y completan la reparación en el lugar. Servicio en Aledo, TX y el área circundante.',
    icon: 'Wrench',
    image: '/images/car-ignition-cylinder-repair-aledo-tx.png',
  },
  {
    slug: 'gm-vats-bypass',
    slugEs: 'bypass-de-vats-gm',
    name: 'GM VATS Bypass & Disable',
    nameEs: 'Bypass y Desactivación de VATS GM',
    shortDesc: 'Professional GM VATS (Vehicle Anti-Theft System) bypass and disable services.',
    shortDescEs: 'Servicios profesionales de bypass y desactivación de VATS (Sistema Antirrobo de Vehículos) GM.',
    description: 'GM\'s VATS (Vehicle Anti-Theft System) and PassKey systems use resistor-chip keys to prevent theft. Over time, the system can malfunction, causing no-start conditions and security lockouts. We provide professional VATS bypass and disable services that permanently resolve these issues. Works on all GM vehicles including Chevrolet, Pontiac, Buick, Cadillac, and Oldsmobile. On-site service in Aledo, TX and nearby areas.',
    descriptionEs: 'El sistema VATS (Sistema Antirrobo de Vehículos) y PassKey de GM usa llaves con chip resistivo para prevenir robos. Con el tiempo, el sistema puede fallar, causando condiciones de no arranque y bloqueos de seguridad. Proporcionamos servicios profesionales de bypass y desactivación de VATS que resuelven estos problemas permanentemente. Funciona en todos los vehículos GM incluyendo Chevrolet, Pontiac, Buick, Cadillac y Oldsmobile. Servicio en el lugar en Aledo, TX y áreas cercanas.',
    icon: 'Key',
    image: '/images/mobile-key-programming-workstation-aledo-tx.png',
  },
  {
    slug: 'dodge-chrysler-win-module',
    slugEs: 'modulo-win-dodge-chrysler',
    name: 'Dodge/Chrysler WIN Module & FOBIK',
    nameEs: 'Módulo WIN y FOBIK Dodge/Chrysler',
    shortDesc: 'WIN module replacement and FOBIK key programming for Dodge and Chrysler vehicles.',
    shortDescEs: 'Reemplazo de módulo WIN y programación de llave FOBIK para vehículos Dodge y Chrysler.',
    description: 'The WIN (Wireless Ignition Node) module in Dodge and Chrysler vehicles handles keyless ignition and FOBIK communication. When it fails, your vehicle won\'t recognize the key fob or start. We replace WIN modules, program FOBIK keys, and restore full ignition function on-site. All Dodge, Chrysler, and Jeep models supported. Serving Aledo, TX and within a 10-mile radius.',
    descriptionEs: 'El módulo WIN (Nodo de Ignición Inalámbrico) en vehículos Dodge y Chrysler maneja la ignición sin llave y la comunicación FOBIK. Cuando falla, su vehículo no reconoce el control remoto ni enciende. Reemplazamos módulos WIN, programamos llaves FOBIK y restauramos la función de ignición completa en el lugar. Todos los modelos Dodge, Chrysler y Jeep soportados. Servicio en Aledo, TX y dentro de un radio de 10 millas.',
    icon: 'Radio',
    image: '/images/key-fob-programming-service-aledo-tx.png',
  },
  {
    slug: 'dodge-chrysler-vin-swap',
    slugEs: 'cambio-de-vin-dodge-chrysler',
    name: 'Dodge/Chrysler VIN Swap & Programming',
    nameEs: 'Cambio de VIN y Programación Dodge/Chrysler',
    shortDesc: 'Professional VIN programming and swap services for Dodge and Chrysler control modules.',
    shortDescEs: 'Servicios profesionales de programación y cambio de VIN para módulos de control Dodge y Chrysler.',
    description: 'When replacing a control module (PCM, BCM, or instrument cluster) on a Dodge, Chrysler, or Jeep vehicle, the new module must have the correct VIN programmed to communicate with the rest of the vehicle\'s systems. We provide professional VIN writing, module syncing, and key programming for all Dodge/Chrysler/Jeep models. No dealer appointment needed — we come to you in Aledo, TX and surrounding areas.',
    descriptionEs: 'Al reemplazar un módulo de control (PCM, BCM o clúster de instrumentos) en un vehículo Dodge, Chrysler o Jeep, el nuevo módulo debe tener el VIN correcto programado para comunicarse con el resto de los sistemas del vehículo. Proporcionamos escritura profesional de VIN, sincronización de módulos y programación de llaves para todos los modelos Dodge/Chrysler/Jeep. Sin necesidad de cita en el concesionario — vamos a usted en Aledo, TX y áreas circundantes.',
    icon: 'FileText',
    image: '/images/mobile-key-programming-workstation-aledo-tx.png',
  },
  {
    slug: 'performance-tuning',
    slugEs: 'afinacion-de-rendimiento',
    name: 'Performance Tuning & ECU Remapping',
    nameEs: 'Afinación de Rendimiento y Remapeo de ECU',
    shortDesc: 'ECU tuning and remapping for more horsepower, torque, and better fuel economy.',
    shortDescEs: 'Afinación y remapeo de ECU para más caballos de fuerza, torque y mejor economía de combustible.',
    description: 'Unlock your vehicle\'s full potential with professional ECU remapping and performance tuning. We adjust fuel maps, ignition timing, boost pressure, and other parameters to deliver noticeable gains in horsepower, torque, and throttle response — while maintaining reliability. Custom tunes available for all makes and models including trucks, sports cars, and diesel vehicles. Serving Aledo, TX and nearby areas.',
    descriptionEs: 'Libere todo el potencial de su vehículo con remapeo profesional de ECU y afinación de rendimiento. Ajustamos mapas de combustible, tiempo de ignición, presión de turbo y otros parámetros para entregar ganancias notables en caballos de fuerza, torque y respuesta del acelerador — manteniendo la confiabilidad. Afinaciones personalizadas disponibles para todas las marcas y modelos incluyendo camionetas, deportivos y vehículos diésel. Servicio en Aledo, TX y áreas cercanas.',
    icon: 'Zap',
    image: '/images/smart-key-diagnostic-tablet-aledo-tx.png',
  },
  {
    slug: 'vw-immo-off',
    slugEs: 'inmovilizador-off-vw',
    name: 'VW Immobilizer Off (IMMO OFF)',
    nameEs: 'Inmovilizador Off VW (IMMO OFF)',
    shortDesc: 'Volkswagen and Audi immobilizer delete and IMMO OFF programming services.',
    shortDescEs: 'Servicios de eliminación de inmovilizador y programación IMMO OFF para Volkswagen y Audi.',
    description: 'Need to swap an ECU on your VW or Audi without going through the dealer\'s immobilizer pairing process? Our IMMO OFF service removes the immobilizer function from the ECU, allowing it to work without key-to-ECU synchronization. Ideal for ECU swaps, standalone engine setups, race builds, and situations where all keys are lost and a new ECU is needed. Serving Aledo, TX and surrounding areas.',
    descriptionEs: 'Necesita cambiar una ECU en su VW o Audi sin pasar por el proceso de emparejamiento del inmovilizador del concesionario? Nuestro servicio IMMO OFF elimina la función del inmovilizador de la ECU, permitiéndole funcionar sin sincronización de llave a ECU. Ideal para cambios de ECU, configuraciones de motor independiente, builds de carreras y situaciones donde se perdieron todas las llaves y se necesita una nueva ECU. Servicio en Aledo, TX y áreas circundantes.',
    icon: 'ShieldOff',
    image: '/images/mobile-key-programming-workstation-aledo-tx.png',
  },
]

export const serviceOptionsEn = [
  'Car Lockout',
  'Car Key Replacement',
  'Key Fob Programming',
  'Transponder Key Programming',
  'Ignition Repair & Replacement',
  'Emergency Car Locksmith (24/7)',
  'Trunk Lockout',
  'Broken Car Key Extraction',
  'Duplicate Car Keys',
  'ECU & Computer Programming',
  'Smart Key & Keyless Entry',
  'ECM/TCM/BCM/ABS Module Programming',
  'Airbag Reset & Crash Module Repair',
  'Mercedes ELV Steering Lock Repair',
  'BMW FRM Footwell Module Repair',
  'Saab Steering Lock Bypass',
  'GM VATS Bypass & Disable',
  'Dodge/Chrysler WIN Module & FOBIK',
  'Dodge/Chrysler VIN Swap & Programming',
  'Performance Tuning & ECU Remapping',
  'VW Immobilizer Off (IMMO OFF)',
]

export const serviceOptionsEs = [
  'Apertura de Auto',
  'Reemplazo de Llave de Auto',
  'Programación de Control Remoto',
  'Programación de Llave Transponder',
  'Reparación y Reemplazo de Ignición',
  'Cerrajero Automotriz de Emergencia (24/7)',
  'Apertura de Cajuela',
  'Extracción de Llave de Auto Rota',
  'Duplicado de Llaves de Auto',
  'Programación de ECU y Computadora',
  'Llave Inteligente y Entrada Sin Llave',
  'Programación de Módulos ECM/TCM/BCM/ABS',
  'Reseteo de Airbag y Reparación de Módulo de Choque',
  'Reparación de Cerradura de Dirección Mercedes ELV',
  'Reparación de Módulo FRM BMW',
  'Bypass de Cerradura de Dirección Saab',
  'Bypass y Desactivación de VATS GM',
  'Módulo WIN y FOBIK Dodge/Chrysler',
  'Cambio de VIN y Programación Dodge/Chrysler',
  'Afinación de Rendimiento y Remapeo de ECU',
  'Inmovilizador Off VW (IMMO OFF)',
]
